import Navbar from "@/components/navbar";
import Appbar from "@/components/appbar";
import type { Metadata } from "next";
import { Provider } from "@/components/providers";

import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="max-w-[400px] mx-auto w-full h-screen">
            <Navbar />
            {children}
            <Appbar />
          </main>
        </Provider>
      </body>
    </html>
  );
}
